#! /usr/bin/env python
from datetime import date

f = 1
#Open file to write#
file1 = open("file.txt", "a")
file2 = open("file.txt", "w")

shop = input("\nGroceries store:\n")
while f == 1:
#Asking user for inputs#
        a = input("\nName:\n")
#While loop until user inserts Integer#
        while True:
           try:
               b = int(input("\nQuantity:\n"))
               break
           except ValueError:
               print("Int, please.")

        c = input("\nPrice:\n")
        d = input("\nPrice to Weight:\n")
        t = date.today()
#Creating a List with user's inputs#
        list = [shop, a, c, d, t]
#Converting the list to a string#
        line = '\t'.join(map(str, list))
#Appending the string to file#
        file1.write(line + "\n")
        file2.write(line + "\n")
#Printing the string for the user#
        print(line, "\n")
#Duplicating if user purchased x>1 of items#
        if b >  1:
                for x in range(b-1):
                        file1.write(line + "\n")
                        file2.write(line + "\n")
                        print(line, "\n")
#Breaking the loop#
        r = input("\nMore? y/n\n")
        if r == 'n':
                break
        elif r == 'y':
                f = 1
        else:
                print("Zio pera hai fatto un bel casino.")
                break

        elif r == 'y':
                f = 1
        else:
                print("Zio pera hai fatto un bel casino.")
                break
